CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nombre VARCHAR(120),
  whatsapp_session VARCHAR(255),
  creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
